# tasks file for roles/python
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install pip
  yum:
    name: python-pip
    state: latest

- name: Pip Install Docker
  pip:
    name: docker
    state: latest